services:
  # =========================
  # Web (Nginx)
  # =========================
  nginx:
    image: nginx:alpine
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - eodi-frontend-net
    ports:
      - "80:80"
    volumes:
      - /opt/eodi/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    mem_limit: 64m

  # =========================
  # Node.js
  # =========================
  node:
    image: 265507129563.dkr.ecr.ap-northeast-2.amazonaws.com/eodi-web:latest
    logging:
      options:
        driver: "json-file"
        max-size: "100m"
        max-file: "5"
    networks:
      - eodi-frontend-net
    mem_limit: 256m
    environment:
      - NODE_OPTIONS=--max-old-space-size=512


  # =========================
  # Application (Spring Boot)
  # =========================
  api:
    image: 265507129563.dkr.ecr.ap-northeast-2.amazonaws.com/eodi-api:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - eodi-frontend-net
    env_file:
      - /opt/eodi/env/api.env
    restart: always
    mem_limit: 512m

networks:
  eodi-frontend-net:
    external: true