services:
  # =========================
  # Database (MySQL)
  # =========================
  mysql:
    image: mysql:8.0
    container_name: eodi-mysql
    networks:
      - eodi-backend-net
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ../../db/mysql/init-scripts:/docker-entrypoint-initdb.d # 초기화 SQL 실행 경로
      - ../../db/mysql/schema:/docker-entrypoint-initdb.d/schema # db schema
    restart: always
    mem_limit: 2g
volumes:
  mysql-data:
networks:
  eodi-backend-net:
    external: true