services:
  # =========================
  # Web (Nginx)
  # =========================
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    mem_limit: 50m

  # =========================
  # Node.js
  # =========================
  node:
    image: eodi-web:latest
    container_name: eodi-web
    command: "npm run start"
    expose:
      - "3000"
    mem_limit: 512m
    environment:
      - NODE_OPTIONS=--max-old-space-size=512


  # =========================
  # Application (Spring Boot)
  # =========================
  app:
    image: eodi-api:latest
    container_name: eodi-app
    env_file:
      - ./app.env
    depends_on:
      - mysql
    restart: always
    mem_limit: 512m

  # =========================
  # Database (MySQL)
  # =========================
  mysql:
    image: mysql:8.0
    container_name: eodi-mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./db.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db/mysql/init-scripts:/docker-entrypoint-initdb.d # 초기화 SQL 실행 경로
      - ../db/mysql/schema:/docker-entrypoint-initdb.d/schema # db schema
    restart: always
    mem_limit: 800m
volumes:
  mysql-data:
