services:
  # =========================
  # Web (Nginx)
  # =========================
  web:
    image: nginx:alpine
    container_name: eodi-web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always
    mem_limit: 256m

  # =========================
  # Application (Spring Boot)
  # =========================
  app:
    image: eodi-api:latest
    container_name: eodi-app
    env_file:
      - ./app.env
    depends_on:
      - mysql
    restart: always
    mem_limit: 1g

  # =========================
  # Database (MySQL)
  # =========================
  mysql:
    image: mysql:8.0
    container_name: eodi-mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./db.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ../db/mysql/init-scripts:/docker-entrypoint-initdb.d # 초기화 SQL 실행 경로
      - ../db/mysql/schema:/docker-entrypoint-initdb.d/schema # db schema
    restart: always
    mem_limit: 1g
volumes:
  mysql-data:
