# 스프링 설정
spring:
  application:
    name: eodi-batch
  datasource:
    url: jdbc:mysql://localhost:3306/eodi_db
    username: eodi_app
    password: eodi_app_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
  jpa:
    hibernate:
      ddl-auto: none         # none, validate, update, create, create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    open-in-view: false      # 배치/백엔드 서비스라면 false 권장
  config:
    import: optional:classpath:.env[.properties]
  main:
    web-application-type: none
  batch:
    job:
      enabled: false

# 애플리케이션 커스텀 설정
eodi:
  batch:
    job-name-prefix: job.name
    job-parameter-prefix: job.parameter.
    force-new-instance-parameter: new
    force-new-instance-parameter-key: run.id
    batch-size: 1000
    job:
      legal-dong-load:
        temp-file-name: LEGAL_DONG_TEMP_FILE
        temp-file-suffix: .json

# 외부 API
api:
  gov-data:
    base-url: http://apis.data.go.kr
    page-size: 500
    key-parameter-name: serviceKey
    key: ${GOV_DATA_API_KEY:default}
    table:
      # 행정안전부 - 법정동 코드 조회
      legal-dong:
        phase: dev
        path: 1741000/StanReginCd/getStanReginCdList
        expiration: 2027-09-05

# 로깅
logging:
  level:
    com.bb: debug
    org.springframework.jdbc.core: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace