# 스프링 설정
spring:
  application:
    name: eodi-batch
  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 15
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none         # none, validate, update, create, create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  config:
    import: optional:classpath:.env[.properties]
  main:
    web-application-type: none
  batch:
    job:
      enabled: false

# 애플리케이션 커스텀 설정
eodi:
  batch:
    runner:
      enabled: true
    job-name-prefix: job.name
    job-parameter-prefix: job.parameter.
    force-new-instance-parameter: new
    batch-size: 1000
    daily-jobs:
      # =========================
      # Address Batch Jobs (20xx)
      # =========================
      - addressUpdateJob               # 20 - 주소 최신화
      - addressPositionUpdateJob       # 21 - 주소 위치정보 최신화

      # =========================
      # Deal Batch Jobs (30xx)
      # =========================
      - dealDataLoadJob                # 30 - 부동산 실거래가 적재 및 최신화
      - dealDataPositionMappingJob     # 31 - 부동산 실거래가 위치 정보 매핑

    job:
      legal-dong-load:
        temp-file-name: LEGAL_DONG_TEMP_FILE
        temp-file-suffix: .json

# 외부 API
api:
  gov-data:
    base-url: http://apis.data.go.kr
    page-size: 500
    key-parameter-name: serviceKey
    key: ${GOV_DATA_API_KEY:default}
    table:
      # 행정안전부 - 법정동 코드 조회
      legal-dong:
        phase: dev
        path: 1741000/StanReginCd/getStanReginCdList
        expiration: 2027-09-05
  juso:
    key: ${JUSO_LINKAGE_API_KEY:default}
# 로깅
logging:
  level:
    com.bb: debug
    org.springframework.jdbc.core: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace