spring:
  application:
    name: eodi-api
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.bb: INFO

external:
  naver:
    base-url: https://m.land.naver.com/map
    default-map-size: 15

springdoc:
  api-docs:
    path: /api-docs      # OpenAPI JSON 문서 경로 (기본: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui    # Swagger UI 경로 (기본: /swagger-ui.html)