spring:
  application:
    name: eodi-api
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.bb: INFO

external:
  naver:
    base-url: https://m.land.naver.com/map
    default-map-size: 15

springdoc:
  api-docs:
    path: /api-docs      # OpenAPI JSON 문서 경로 (기본: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui    # Swagger UI 경로 (기본: /swagger-ui.html)