spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eodi_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: eodi_app
    password: eodi_app_pw
    driver-class-name: com.mysql.cj.jdbc.Driver