spring:
  application:
    name: eodi-api
  datasource:
    url: jdbc:mysql://localhost:3306/eodi_db
    username: eodi_app
    password: eodi_app_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc: 1000

logging:
  level:
    org.springframework: debug
    com.bb: debug

external:
  naver:
    base-url: https://m.land.naver.com/map
    default-map-size: 15

springdoc:
  api-docs:
    path: /api-docs      # OpenAPI JSON 문서 경로 (기본: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui    # Swagger UI 경로 (기본: /swagger-ui.html)