services:
  # =========================
  # Database (MySQL)
  # =========================
  mysql:
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - /opt/eodi/env/db.env
    volumes:
      - /data/db:/var/lib/mysql
    restart: always
    mem_limit: 1g
