name: Backend CI - Build & Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/backend-build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/backend-deploy.yml
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
